### ISSUE TITLE
Does the graph transformer take graph connectivity into account?

### ISSUE THREAD

**Issue by nihalsid** [cvignac/DiGress#49]
Hi, thanks for the great work! 

Looking at NodeEdgeBlock layer it seems that the attention is applied assuming full connectivity in the graph (except for invalid nodes masked out by node_mask). Is this the case? If so, is there a reason why you didnt go with the graph attention layer implementation [here](https://github.com/graphdeeplearning/graphtransformer/blob/c9cd49368eed4507f9ae92a137d90a7a9d7efc3a/layers/graph_transformer_layer.py#LL34C7-L34C30) that takes into account the connectivity?

Thanks!
Yawar

**Comment by cvignac** [comment]
DiGress makes predictions for all pairs of nodes, so it makes sense to use all pairs of nodes to perform the message-passing as well. For small molecules, considering all pairs is very common, and actually yields the best performance. 


If you work with larger graphs, you might want to replace the transformer layer in order to reduce the GPU use, but I don't know how it will affect performance.

**Comment by nihalsid** [comment]
Thanks for the quick response!
