### ISSUE TITLE
Discrepancy between the paper and the guidance branch's readme?

### ISSUE THREAD

**Issue by Asduffo** [cvignac/DiGress#63]
Hello
I have noticed one thing: in the guidance branch's readme, you explicitly instruct the user to train the unconditional model without extra features:
"Train an unconditional model without extra features, for example: `python3 main.py +experiment=test`"
However, the paper's algorithm 3 on page 7 clearly uses the extra features:
$z \leftarrow f (G^t , t)$ (Structural and spectral features)
$\widehat{p}^X, \widehat{p}^E \leftarrow \phi_{\theta}(G^t, z)$ (Forward pass)

Did I miss something? And regardless, did you use them in the experiments you have shown in your paper?

**Comment by cvignac** [comment]
It's a mistake in the paper, the unconditional model should not use the extra feature. The reason is that later we take the gradient with respect to X and E, and we would like these gradients to be as informative as possible. Since the extra features are not differentiable, we prefer not to use them.
